server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/music?serverTimezone=Asia/Shanghai&userUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: "001314"
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    servlet:
      multipart:
        max-file-size: 50MBs
        max-request-size: 50MB

# Mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.yin.domain




#spring.datasource.url=jdbc:mysql://localhost:3306/music?serverTimezone=Asia/Shanghai
#spring.datasource.username=root
#spring.datasource.password=001314
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#
#mybatis.typeAliasesPackage=com.example.yin.domain
#mybatis.mapperLocations=classpath:mapper/*.xml
#
#spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
#spring.jackson.time-zone=GMT+8
#
#spring.server.MaxFileSize=50MB
#spring.server.MaxRequestSize=50MB
#server.port=8888
#
##热部署生效
#spring.devtools.restart.enabled=true
#
##设置重启的目录
#spring.devtools.restart.additional-paths=src/main/java
#
##classpath目录下的WEB-INF文件夹内容修改不重启
#spring.devtools.restart.exclude=WEB-INF/**
