server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/music?serverTimezone=Asia/Shanghai&userUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: "001314"
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    servlet:
      multipart:
        max-file-size: 50MBs
        max-request-size: 50MB

# Mybatis-plus配置
mybatis:
  # 配置Mapper映射文件
  mapper-locations: classpath:/mapper/*Mapper.xml
  # 配置Mybatis数据返回类型别名(默认别名是类名)
  type-aliases-package: com.rich.music.domain
  configuration:
    # 自动驼峰命名
    map-underscore-to-camel-case: false

# Mybatis SQL 打印(方法接口所在的包，不是Mapper.xml所在的包)
logging:
  level:
    com.rich.music.dao: debug

jwt:
  # JWT 存储请求头
  tokenHeader: Authorization
  # JWT 加解密使用的密钥
  secret: duolaimi
  # JWT的超期限时间(60*60*24)
  expiration: 604800
  # JWT 负载中拿到开头
  tokenHead: Bearer